### ISSUE TITLE
Suggestion: .putdocignore

### ISSUE THREAD

**Issue by rolfn** [natevw/putdoc#1]
It would be nice to have a configuration file `.putdocignore` similar to `.gitignore` containing all files and directories to be ignored. I run in trouble e.g. with editor backup files like `myfile.json~`. I suppose that the following package can be used for this task: [node-ignore](/kaelzhang/node-ignore) Thanks in advance.

**Comment by natevw** [comment]
Thanks for this idea, and for the pull request! Following the .gitignore syntax is reasonable, however, I think it would be better to implement this as [.couchappignore](http://couchapp.readthedocs.io/en/latest/couchapp/config.html#couchappignore) (also documented [here](https://github.com/couchapp/couchapp/wiki/.couchappignore)) instead. I mean not just the format, but also re-use the name.

Not only does this help towards compatibility with existing CouchApps, it's defined as:

> a simple json file containing an array of regexps

…so it might not require another dependency, but still be relatively simple to implement inline.

What do you think?

**Comment by rolfn** [comment]
I have no problems with this solution.

**Comment by natevw** [comment]
Hoping to tackle it this afternoon.

Also found https://github.com/couchapp/couchapp/issues/204 while researching some of the details here (can .couchappignore appear in subfolders? what exactly does it match against?)

**Comment by natevw** [comment]
The Python project's handling of .couchappignore is kinda weird to me, it matches in an achored-to-start way, and only against each single path component. This severely limits what it can do, especially compared to the power of gitignore.

Here's my plan:

* array of regexes like couchapp, but matched against full (relative) path
* just one .couchappignore (at project root) for now at least

I think this keeps things simple, should be mostly backwards compatible with couchapp in practice, but also adds some putdoc-specific power if people want to use it.

(I'm hoping the Python couchapp could follow suit with the "match against relative path" logic.)

**Comment by natevw** [comment]
I added .couchappignore support per the comment above.

Published as `putdoc@2.0.0` since it's technically a breaking change if `excludeDirs` was considered public API. (I guess v2 also marks a shift in my thinking from "quick hack upload tool I needed" to "simple tool that can upload most couchapps"… ;-)
